name       : frozen-bubble
version    : 2.2.1_1
release    : 1
source     :
    - http://www.frozen-bubble.org/data/frozen-bubble-2.2.1-beta1.tar.bz2 : c5be403ccb71543dab1aeb7d5ae311e18693f79937fb9159469cdad0abf18ac4
license    : GPL-2.0-or-later
component  : games.arcade
summary    : A game in which you throw colorful bubbles and build groups to destroy the bubbles
description: |
    Colorful 3D rendered penguin animations, 100 levels of 1p game, hours and hours of 2p game, nights and nights of 2p/3p/4p/5p game over LAN or Internet, a level-editor, 3 professional quality digital soundtracks, 15 stereo sound effects, 8 unique graphical transition effects, 8 unique logo eye-candies.
builddeps  :
    - pkgconfig(SDL_image)
    - pkgconfig(SDL_mixer)
    - pkgconfig(SDL_Pango)
    - perl-alien-sdl
    - perl-file-slurp
    - perl-ipc-system-simple
    - perl-locale-maketext-lexicon
    - perl-module-build
    - perl-sdl
rundeps    :
    - perl-alien-sdl
    - perl-compress-bzip2
    - perl-file-which
    - perl-tie-simple
    - perl-sdl
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-buffer-size-when-formatting-current-date.patch

    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install

    for i in 16x16 32x32 48x48 64x64; do
        install -Dm00644 share/icons/frozen-bubble-icon-${i}.png $installdir/%PREFIX%/share/icons/hicolor/${i}/apps/frozen-bubble.png
    done
    install -Dm00644 $pkgfiles/frozen-bubble.desktop $installdir/%PREFIX%/share/applications/frozen-bubble.desktop
check      : |
    perl Build test
